name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Downgrade to Python 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential python3-setuptools
        pip install buildozer cython

    - name: Build APK
      run: |
        sudo apt-get install -y openjdk-8-jdk
        buildozer android debug
        mv ./bin/*.apk ${{ github.workspace }}/FRSapp.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: FRSapp-debug.apk
        path: ${{ github.workspace }}/FRSapp.apk
